language: node_js
node_js:
  - "node"
notifications:
  email: false

cache:
  # cache both npm modules and Cypress binary
  directories:
    - ~/.npm
    - ~/.cache
  override:
    - npm ci
    - npm run cy:verify
script:
- npm test
- npm run start:ci & 
- npm run cy:run --record --record --key 046e5145-7aae-4a30-872a-28aa682d794b"
- CI='' npm run build